### PR TITLE
Add timeOfContact column to contacts

### PR DESCRIPTION
**Pull request by GPaoloni**
Jira: https://bugs.benetech.org/browse/CHI-337

This PR is related to https://github.com/tech-matters/flex-plugins/pull/242

This PR:
- adds migration for `timeOfContact` column (Contacts).
- fixes error where `accountSid` was not being recorded even if provided.

### CODE REVIEW

**Comment by GPaoloni** [comment]
While the date search is now against `timeOfContact`, the contacts are returned order like:
`order: [['createdAt', 'DESC']],`
Should we sort them by `timeOfContact` instead? (I think that we should populate this column with `createdAt` after running the migration).

**Comment by nickhurlburt** [comment]
> Should we sort them by timeOfContact instead? (I think that we should populate this column with createdAt after running the migration).

Yes to both.

**Review by nickhurlburt — COMMENTED** [review]
This looks like what we'd expect, but a couple questions:
- do we need to update swagger?
- are we going to require that a `timeOfContact` is sent from the frontend, or do we default to the `createdAt` time if it is missing?  (I don't have a preference, just want to know what we plan)

**Review by andvirga — APPROVED** [review]
Looks good to me!

**Comment by GPaoloni** [comment]
Deployed to staging.

**Pull request merged**
