### PR TITLE
Add ability to search by Office

### PR DESCRIPTION
**Pull request by andvirga**
Jira: https://bugs.benetech.org/browse/CHI-529

Related to `flex-plugins` changes in: https://github.com/tech-matters/flex-plugins/pull/385

Primary reviewer: @murilovmachado 

Changes description:
- Modified contacts and cases queries to filter by helpline attribute. If this attribute is not provided, then the system should return contacts and cases from all helplines.

### CODE REVIEW

**Review by GPaoloni — APPROVED** [review]
Looks good to me. Just a few considerations:
- If there are records with `helpline = null`, nobody will be able to retrieve those. We should look for this cases and update them accordingly I believe.
- The fact that all helplines were able to retrieve `helpline = ''` and `helpline = null` records was due to Joan inputing contacts & cases for helplines to test in Beta. Just to be aware that we should notify this, as helpline's users wont see them anymore.

**Comment by nickhurlburt** [comment]
I want to echo @GPaoloni's comments above.  We need to make sure that Beta and Development will continue to work.  Specifically:

> The fact that all helplines were able to retrieve helpline = '' and helpline = null records was due to Joan inputing contacts & cases for helplines to test in Beta. Just to be aware that we should notify this, as helpline's users wont see them anymore.

I think it's okay if Joan's old contacts and cases with `helpline = ''` or `null` don't appear for all helplines, since those have been deleted anyway.  But we should make sure Dee and Joan understand the new behavior.

> If there are records with helpline = null, nobody will be able to retrieve those. 

Won't this mean that all contacts and cases entered by our staff on Beta and Development will be lost?

Also,
> Modified contacts and cases queries to filter by helpline attribute. If this attribute is not provided, then the system should return contacts and cases from all helplines.

The option to return contacts and cases from all helplines should have some sort of permissions control on it, so that not everyone can do it.  This is a good thing to ask @dee-luo and @murilovmachado about.

**Comment by andvirga** [comment]
@GPaoloni @nickhurlburt 
About `helpline = ''` and `helpline = null` contacts and cases.
After checking again I can confirm that these records will be shown only if the user has no helpline attribute set.

**Case-Controller**
In line 103 of `case-controller.js` we're doing this:

`helpline: body.helpline || null`
Therefore if we send `''` as `body.helpline` value this comparison will set `null` to `helpline`.

Then in line 55 we're evaluating that value to build the query:

```javascript
    queryObject.where = {
      [Op.and]: [helpline && { helpline }, accountSid && { accountSid }],
    };
```
Since `helpline` is `null` we're not applying this filter.

@nickhurlburt is this the expected behavior? From my understanding, I believe that it is since we don't want to lose the current data from Aselo Beta.

**Comment by nickhurlburt** [comment]
@andvirga that's definitely fine to get onto Development and fine for South Africa and Zambia.  I'll follow up in Slack with more.

**Pull request merged**
