### PR TITLE
Return connected contacts with cases

### PR DESCRIPTION
**Pull request by murilovmachado**
Jira: https://bugs.benetech.org/browse/CHI-281

This PR:
- Returns case object with **connectedContacts** prepopulated
- **GET /cases** only returns cases that have connected contacts (no ghost cases)

### CODE REVIEW

**Review by nickhurlburt — APPROVED** [review]
Looks good!  It's great that Sequelize supports this so naturally.

One thing to consider -- should we upgrade to [Sequelize 6](https://sequelize.org/master/manual/upgrade-to-v6.html)?  At first glance, it looks like we wouldn't hit many backward compatibility issues with our existing usage.  If this looks like just a few hours or less to upgrade, I'd suggest doing it now.  Otherwise we can create an issue to do it later.

**Comment by nickhurlburt** [comment]
One other suggestion -- please name the PR something more natural, like 'Return connected contacts with cases'.  Just going with the auto-suggestion from the branch name make it look strange.

**Comment by murilovmachado** [comment]
> One thing to consider -- should we upgrade to [Sequelize 6](https://sequelize.org/master/manual/upgrade-to-v6.html)? At first glance, it looks like we wouldn't hit many backward compatibility issues with our existing usage. If this looks like just a few hours or less to upgrade, I'd suggest doing it now. Otherwise we can create an issue to do it later.

I've just checked, and there's actually one breaking change that would affect us:
- `sequelize.import` method has been removed.

In this case, I would suggest creating a Jira task to do it separately.

**Comment by nickhurlburt** [comment]
Okay -- Jira task created.

**Pull request merged**
